<?php

namespace App\Enums;

enum ApiErrorCode: string
{
    case AUTH_REQUIRED = 'AUTH_REQUIRED';
    case NONCE_REPLAY = 'NONCE_REPLAY';
    case TIMESTAMP_OUT_OF_WINDOW = 'TIMESTAMP_OUT_OF_WINDOW';
    case DEVICE_MISMATCH = 'DEVICE_MISMATCH';
    case DEVICE_NOT_BOUND = 'DEVICE_NOT_BOUND';
    case LICENSE_INVALID = 'LICENSE_INVALID';
    case LICENSE_INEFFECTIVE = 'LICENSE_INEFFECTIVE';
    case INVALID_CHANNEL = 'INVALID_CHANNEL';
    case INVALID_VERSION = 'INVALID_VERSION';
    case PACKAGE_NOT_FOUND = 'PACKAGE_NOT_FOUND';
    case SERVER_ERROR = 'SERVER_ERROR';
}
